// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CodeBlock = {
    _type: "codeBlock";
    code?: string;
    language?:
        | "typescript"
        | "javascript"
        | "tsx"
        | "html"
        | "css"
        | "json"
        | "groq"
        | "bash"
        | "markdown"
        | "yaml"
        | "graphql"
        | "sql"
        | "python"
        | "text";
    filename?: string;
};

export type SanityImageAssetReference = {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    focusKeyword?: string;
    keywords?: Array<string>;
    image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    noIndex?: boolean;
};

export type ChangelogEntry = {
    _id: string;
    _type: "changelogEntry";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    date: string;
    type: "feature" | "improvement" | "fix" | "content" | "infrastructure";
    summary: string;
    body?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?: "normal" | "h3" | "h4";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
    }>;
    relatedProject?: "alignsd" | "ctrl" | "ripemetrics" | "arndvs";
    commitHash?: string;
    commitRange?: string;
    isHighlight?: boolean;
    source?: "manual" | "automated";
};

export type Slug = {
    _type: "slug";
    current: string;
    source?: string;
};

export type Post = {
    _id: string;
    _type: "post";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    author?: string;
    publishedAt?: string;
    excerpt?: string;
    tldr?: string;
    mainImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
    };
    body?: Array<
        | {
              children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                  href?: string;
                  blank?: boolean;
                  _type: "link";
                  _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
          }
        | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt: string;
              caption?: string;
              _type: "inlineImage";
              _key: string;
          }
        | ({
              _key: string;
          } & CodeBlock)
    >;
    categories?: Array<string>;
    seo?: Seo;
    aiEnhancement?: {
        status?: "pending" | "completed" | "failed";
        lastRunAt?: string;
        confidence?: number;
        model?: string;
    };
};

export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top: number;
    bottom: number;
    left: number;
    right: number;
};

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x: number;
    y: number;
    height: number;
    width: number;
};

export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height: number;
    width: number;
    aspectRatio: number;
};

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    thumbHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};

export type AllSanitySchemaTypes =
    | CodeBlock
    | SanityImageAssetReference
    | Seo
    | ChangelogEntry
    | Slug
    | Post
    | SanityImageCrop
    | SanityImageHotspot
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(publishedAt)] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    publishedAt,    mainImage {      ...,      asset-> { _id, url, metadata { dimensions, lqip } }    },    categories,    "bodyCharCount": length(pt::text(body))  }
export type POSTS_QUERY_RESULT = Array<{
    _id: string;
    title: string;
    slug: Slug;
    excerpt: string | null;
    publishedAt: string;
    mainImage: {
        asset: {
            _id: string;
            url: string;
            metadata: {
                dimensions: SanityImageDimensions | null;
                lqip: string | null;
            } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
    } | null;
    categories: Array<string> | null;
    bodyCharCount: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    _updatedAt,    title,    slug,    author,    publishedAt,    excerpt,    tldr,    mainImage {      ...,      asset-> { _id, url, metadata { dimensions, lqip } }    },    body[] {      ...,      _type == "image" => {        ...,        asset-> { _id, url, metadata { dimensions, lqip } }      }    },    "bodyCharCount": length(pt::text(body)),    categories,    seo {      ...,      image { ..., asset-> { _id, url, metadata { dimensions } } }    }  }
export type POST_QUERY_RESULT = {
    _id: string;
    _updatedAt: string;
    title: string;
    slug: Slug;
    author: string | null;
    publishedAt: string | null;
    excerpt: string | null;
    tldr: string | null;
    mainImage: {
        asset: {
            _id: string;
            url: string;
            metadata: {
                dimensions: SanityImageDimensions | null;
                lqip: string | null;
            } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
    } | null;
    body: Array<
        | {
              children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
              }>;
              style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                  href?: string;
                  blank?: boolean;
                  _type: "link";
                  _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
          }
        | {
              _key: string;
              _type: "codeBlock";
              code?: string;
              language?:
                  | "bash"
                  | "css"
                  | "graphql"
                  | "groq"
                  | "html"
                  | "javascript"
                  | "json"
                  | "markdown"
                  | "python"
                  | "sql"
                  | "text"
                  | "tsx"
                  | "typescript"
                  | "yaml";
              filename?: string;
          }
        | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt: string;
              caption?: string;
              _type: "inlineImage";
              _key: string;
          }
    > | null;
    bodyCharCount: number;
    categories: Array<string> | null;
    seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        focusKeyword?: string;
        keywords?: Array<string>;
        image: {
            asset: {
                _id: string;
                url: string;
                metadata: {
                    dimensions: SanityImageDimensions | null;
                } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        } | null;
        noIndex?: boolean;
    } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)][].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/sanity/lib/queries.ts
// Variable: SITEMAP_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] {    "slug": slug.current,    _updatedAt  }
export type SITEMAP_POSTS_QUERY_RESULT = Array<{
    slug: string;
    _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CHANGELOG_QUERY
// Query: *[_type == "changelogEntry"] | order(date desc) [0...50] {    _id,    title,    slug,    date,    type,    summary,    body,    relatedProject,    commitHash,    commitRange,    isHighlight,    source  }
export type CHANGELOG_QUERY_RESULT = Array<{
    _id: string;
    title: string;
    slug: Slug;
    date: string;
    type: "content" | "feature" | "fix" | "improvement" | "infrastructure";
    summary: string;
    body: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?: "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
    }> | null;
    relatedProject: "alignsd" | "arndvs" | "ctrl" | "ripemetrics" | null;
    commitHash: string | null;
    commitRange: string | null;
    isHighlight: boolean | null;
    source: "automated" | "manual" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CHANGELOG_LATEST_DATE_QUERY
// Query: *[_type == "changelogEntry"] | order(date desc) [0].date
export type CHANGELOG_LATEST_DATE_QUERY_RESULT = string | null;

declare module "@sanity/client" {
    interface SanityQueries {
        '\n  *[_type == "post" && defined(publishedAt)] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    publishedAt,\n    mainImage {\n      ...,\n      asset-> { _id, url, metadata { dimensions, lqip } }\n    },\n    categories,\n    "bodyCharCount": length(pt::text(body))\n  }\n': POSTS_QUERY_RESULT;
        '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    _updatedAt,\n    title,\n    slug,\n    author,\n    publishedAt,\n    excerpt,\n    tldr,\n    mainImage {\n      ...,\n      asset-> { _id, url, metadata { dimensions, lqip } }\n    },\n    body[] {\n      ...,\n      _type == "image" => {\n        ...,\n        asset-> { _id, url, metadata { dimensions, lqip } }\n      }\n    },\n    "bodyCharCount": length(pt::text(body)),\n    categories,\n    seo {\n      ...,\n      image { ..., asset-> { _id, url, metadata { dimensions } } }\n    }\n  }\n': POST_QUERY_RESULT;
        '\n  *[_type == "post" && defined(slug.current)][].slug.current\n': POST_SLUGS_QUERY_RESULT;
        '\n  *[_type == "post" && defined(slug.current)] {\n    "slug": slug.current,\n    _updatedAt\n  }\n': SITEMAP_POSTS_QUERY_RESULT;
        '\n  *[_type == "changelogEntry"] | order(date desc) [0...50] {\n    _id,\n    title,\n    slug,\n    date,\n    type,\n    summary,\n    body,\n    relatedProject,\n    commitHash,\n    commitRange,\n    isHighlight,\n    source\n  }\n': CHANGELOG_QUERY_RESULT;
        '\n  *[_type == "changelogEntry"] | order(date desc) [0].date\n': CHANGELOG_LATEST_DATE_QUERY_RESULT;
    }
}
